// A bunch of information about the player
#define PLAYER_MOVEMENT_TYPE_2FRAME 0
#define PLAYER_MOVEMENT_TYPE_3FRAME 1

#define PLAYER_MOVEMENT_STYLE_LOOSE 0
#define PLAYER_MOVEMENT_STYLE_GRID 1

// ----- RETRO INTERACTIVE CODE REPLACEMENT -----
// ----- Changes in this area are discouraged and may be lost! -----
    #define RI_PLAYER_MOVEMENT_TYPE_DEF PLAYER_MOVEMENT_TYPE_3FRAME
    #define RI_PLAYER_MOVEMENT_SPEED_INT 20
    #define RI_PLAYER_STARTING_HEALTH_INT 6
    #define RI_PLAYER_STARTING_MAX_HEALTH_INT 6
    #define RI_PLAYER_INVULN_TIME_INT 30
    #define RI_PLAYER_MOVEMENT_STYLE PLAYER_MOVEMENT_STYLE_GRID
// ----- END RETRO INTERACTIVE CODE REPLACEMENT ----- 